require("dotenv").config();
// console.log("DB_PASSWORD:", process.env.DB_PASSWORD);
// console.log("Type:", typeof process.env.DB_PASSWORD);
// require("dotenv").config({ path: require("path").join(__dirname, "../.env") });
const { Pool } = require("pg");
const argon2   = require("argon2");

/**
 * NexMart — Database Seed Script
 * Inserts 50 products across 8 categories + 1 admin user
 *
 * Run:  node nexmart/sql/seed.js
 * Requires your .env to be filled in first.
 */



const pool = new Pool({
  host:     process.env.DB_HOST     || "localhost",
  port:     Number(process.env.DB_PORT) || 5432,
  database: process.env.DB_NAME     || "nexmart",
  user:     process.env.DB_USER     || "postgres",
  password: process.env.DB_PASSWORD || "",
});

// ─── PRODUCTS ─────────────────────────────────────────────────────────────────
const PRODUCTS = [
  // ── Electronics (12 products) ───────────────────────────────────────────────
  {
    name:          "Sony WH-1000XM5 Wireless Headphones",
    description:   "Industry-leading noise cancellation with the Sony WH-1000XM5. Features 30-hour battery life, Speak-to-Chat technology, and multipoint connection. Folds flat for easy carrying.",
    price:         185000,
    original_price:245000,
    category:      "electronics",
    category_name: "Electronics",
    brand:         "Sony",
    images:        [
      "https://www-konga-com-res.cloudinary.com/image/upload/f_auto,q_auto,w_1200,c_limit/media/catalog/product/F/J/67343_1740845880.jpg",
      "https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/05/2942914/1.jpg?7731",
      "https://www-konga-com-res.cloudinary.com/image/upload/f_auto,q_auto,w_1200,c_limit/media/catalog/product/J/Y/67343_1740845902.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:true,
    stock:         45,
    specs:         { "Driver Size": "30mm", "Frequency Response": "4Hz-40kHz", "Battery Life": "30 hours", "Weight": "250g", "Connectivity": "Bluetooth 5.2" },
    tags:          ["headphones", "wireless", "noise-cancelling", "sony"],
    rating:        4.8,
    review_count:  312,
  },
  {
    name:          "Apple MacBook Pro 14\" M3 Pro",
    description:   "The MacBook Pro 14-inch with M3 Pro chip delivers exceptional performance with up to 22 hours battery life. Features Liquid Retina XDR display, 18GB unified memory, 512GB SSD.",
    price:         980000,
    original_price:1150000,
    category:      "electronics",
    category_name: "Electronics",
    brand:         "Apple",
    images:        [
      "https://i.ebayimg.com/images/g/h1cAAOSwE9ZlVbqV/s-l1600.webp",
      "https://i.ebayimg.com/images/g/~AAAAOSwQ~tlVbqU/s-l1600.webp",
      "https://i.ebayimg.com/images/g/dvsAAOSwHytlVbqR/s-l1600.webp",
      "https://i.ebayimg.com/images/g/WIEAAOSwehVlVbqS/s-l1600.webp",
      "https://i.ebayimg.com/images/g/ZZwAAOSwgXhlVbqT/s-l1600.webp",
      "https://i.ebayimg.com/images/g/dsoAAOSwN59lVbqT/s-l1600.webp",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:true,
    stock:         18,
    specs:         { "Chip": "Apple M3 Pro", "Memory": "18GB", "Storage": "512GB SSD", "Display": "14.2\" Liquid Retina XDR", "Battery": "Up to 22 hours" },
    tags:          ["laptop", "macbook", "apple", "m3"],
    rating:        4.9,
    review_count:  188,
  },
  {
    name:          "Samsung Galaxy S24 Ultra",
    description:   "Samsung's most powerful smartphone ever. Features built-in S Pen, 200MP camera, 12GB RAM, and Snapdragon 8 Gen 3. Titanium frame with 5000mAh battery.",
    price:         620000,
    original_price:720000,
    category:      "electronics",
    category_name: "Electronics",
    brand:         "Samsung",
    images:        [
      "https://www-konga-com-res.cloudinary.com/image/upload/f_auto,q_auto,w_1200,c_limit/media/catalog/product/C/I/163129_1745704873.jpg",
      "https://www-konga-com-res.cloudinary.com/image/upload/f_auto,q_auto,w_1200,c_limit/media/catalog/product/F/M/163129_1745705124.jpg",
      "https://www-konga-com-res.cloudinary.com/image/upload/f_auto,q_auto,w_1200,c_limit/media/catalog/product/B/C/163129_1745705164.jpg",
      "https://www-konga-com-res.cloudinary.com/image/upload/f_auto,q_auto,w_1200,c_limit/media/catalog/product/I/R/163129_1745705079.jpg",
      "https://www-konga-com-res.cloudinary.com/image/upload/f_auto,q_auto,w_1200,c_limit/media/catalog/product/M/Z/163129_1745705099.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:true,
    stock:         30,
    specs:         { "Display": "6.8\" Dynamic AMOLED 2X", "Camera": "200MP main", "RAM": "12GB", "Storage": "256GB", "Battery": "5000mAh" },
    tags:          ["smartphone", "samsung", "galaxy", "s-pen"],
    rating:        4.7,
    review_count:  254,
  },
  {
    name:          "PlayStation 5 Console (Disc Edition)",
    description:   "Experience lightning-fast loading with custom SSD, deeper immersion with Haptic feedback, and a new generation of incredible PlayStation games.",
    price:         450000,
    original_price:500000,
    category:      "electronics",
    category_name: "Electronics",
    brand:         "Sony",
    images:        [
      "https://i.ebayimg.com/images/g/qy8AAOSwwB9ldsi6/s-l960.webp",
      "https://i.ebayimg.com/images/g/2iIAAeSwpfdqPyF-/s-l1600.webp",
      "https://i.ebayimg.com/images/g/bogAAeSwyxBqPyF8/s-l1600.webp",
      "https://i.ebayimg.com/images/g/NSgAAeSwKIxqPyFm/s-l1600.webp",
    ],
    badge:         "hot",
    is_new:        false,
    is_best_seller:true,
    stock:         12,
    specs:         { "CPU": "AMD Zen 2, 8 cores", "GPU": "10.28 TFLOPS", "Storage": "825GB SSD", "RAM": "16GB GDDR6", "Optical Drive": "Ultra HD Blu-ray" },
    tags:          ["playstation", "gaming", "ps5", "console"],
    rating:        4.9,
    review_count:  421,
  },
  {
    name:          "Apple iPad Pro 12.9\" M2",
    description:   "The ultimate iPad experience with M2 chip, Liquid Retina XDR display with ProMotion, and Wi-Fi 6E. Perfect for creative professionals on the go.",
    price:         540000,
    original_price:null,
    category:      "electronics",
    category_name: "Electronics",
    brand:         "Apple",
    images:        [
      "https://i.ebayimg.com/images/g/-EYAAeSwmmlqC9J7/s-l1600.webp",
      "https://i.ebayimg.com/images/g/XkwAAeSwh5VqC9J7/s-l1600.webp",
      "https://i.ebayimg.com/images/g/7poAAeSw9aNqC9J7/s-l1600.webp",
      "https://i.ebayimg.com/images/g/nikAAeSweUZqC9J7/s-l1600.webp",
    ],
    badge:         "new",
    is_new:        true,
    is_best_seller:false,
    stock:         22,
    specs:         { "Chip": "Apple M2", "Display": "12.9\" Liquid Retina XDR", "Storage": "256GB", "Camera": "12MP Wide + 10MP Ultra Wide", "Connectivity": "Wi-Fi 6E, 5G" },
    tags:          ["ipad", "apple", "tablet", "m2"],
    rating:        4.8,
    review_count:  97,
  },
  {
    name:          "JBL Flip 6 Portable Bluetooth Speaker",
    description:   "Powerful sound in a compact, waterproof package. The JBL Flip 6 features IP67 rating, 12 hours playtime, and PartyBoost for connecting multiple speakers.",
    price:         45000,
    original_price:58000,
    category:      "electronics",
    category_name: "Electronics",
    brand:         "JBL",
    images:        [
      "https://vanaplus.co/image/cache/catalog/Micropack-Rechargeable-2-4G-Bluetooth-Wireless-Mouse-ML-203W%20(93)-1100x1100.png",
      "https://vanaplus.co/image/cache/catalog/Micropack-Rechargeable-2-4G-Bluetooth-Wireless-Mouse-ML-203W%20(94)-1100x1100.png",
      "https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/18/0863914/1.jpg?3133",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         60,
    specs:         { "Output Power": "30W", "Battery Life": "12 hours", "Waterproof": "IP67", "Frequency": "63Hz-20kHz", "Weight": "550g" },
    tags:          ["speaker", "bluetooth", "jbl", "portable", "waterproof"],
    rating:        4.6,
    review_count:  189,
  },
  {
    name:          "LG 55\" OLED evo C3 4K Smart TV",
    description:   "Perfect blacks and stunning colors with LG OLED evo technology. Features α9 AI Processor Gen6, Dolby Vision IQ, Dolby Atmos, and webOS 23.",
    price:         780000,
    original_price:920000,
    category:      "electronics",
    category_name: "Electronics",
    brand:         "LG",
    images:        [
      "https://www.lg.com/content/dam/channel/wcms/uk/tv-audio-video/tv-soundbar/oled-evo/c5/oled55c56/_2010x1334_ENG_OLED55C.jpg/jcr:content/renditions/thum-1600x1062.jpeg?w=800",
      "https://www.lg.com/content/dam/channel/wcms/uk/tv-audio-video/tv-soundbar/oled-evo/c5/oled55c56/OLED55C56LB_2010x1334_1.jpg/jcr:content/renditions/thum-1600x1062.jpeg?w=800",
      "https://www.lg.com/content/dam/channel/wcms/uk/tv-audio-video/tv-soundbar/webos-image/_2010x1334_WebOS.jpg/jcr:content/renditions/thum-1600x1062.jpeg?w=800",
      "https://www.lg.com/content/dam/channel/wcms/uk/tv-audio-video/tv-soundbar/oled-evo/c5/oled55c56/OLED55C56LB_2010x1334_6.jpg/jcr:content/renditions/thum-1600x1062.jpeg?w=800",
      "https://www.lg.com/content/dam/channel/wcms/uk/tv-audio-video/tv-soundbar/oled-evo/c5/oled55c56/OLED55C56LB_2010x1334_13.jpg/jcr:content/renditions/thum-1600x1062.jpeg?w=800",
      "https://www.lg.com/content/dam/channel/wcms/uk/tv-audio-video/tv-soundbar/oled-evo/c5/oled55c56/OLED55C56LB_2010x1334_14.jpg/jcr:content/renditions/thum-1600x1062.jpeg?w=800",
      "https://www.lg.com/content/dam/channel/wcms/uk/tv-audio-video/tv-soundbar/oled-evo/c5/oled55c56/OLED55C56LB_2010x1334_12.jpg/jcr:content/renditions/thum-1600x1062.jpeg?w=800",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         8,
    specs:         { "Screen Size": "55 inches", "Panel": "OLED evo", "Resolution": "4K Ultra HD", "HDR": "Dolby Vision IQ, HDR10", "Audio": "60W, Dolby Atmos" },
    tags:          ["tv", "oled", "lg", "smart-tv", "4k"],
    rating:        4.7,
    review_count:  76,
  },
  {
    name:          "Xiaomi Redmi Note 13 Pro+",
    description:   "200MP camera flagship killer with 120W HyperCharge. Features 6.67\" AMOLED display at 120Hz, Snapdragon 7s Gen 2, and IP68 water resistance.",
    price:         195000,
    original_price:220000,
    category:      "electronics",
    category_name: "Electronics",
    brand:         "Xiaomi",
    images:        [
      "https://i.ebayimg.com/images/g/8CgAAOSwhFpma-vr/s-l1600.webp",
      "https://i.ebayimg.com/images/g/n7sAAOSwThhma-vu/s-l1600.webp",
      "https://i.ebayimg.com/images/g/FQQAAOSwkf5ma-vw/s-l1600.webp",
      "https://i.ebayimg.com/images/g/DEkAAOSwkCRma-v0/s-l1600.webp",
      "https://i.ebayimg.com/images/g/jHsAAOSw8yVma-v3/s-l1600.webp",
    ],
    badge:         "new",
    is_new:        true,
    is_best_seller:false,
    stock:         55,
    specs:         { "Display": "6.67\" AMOLED 120Hz", "Camera": "200MP main", "Chipset": "Snapdragon 7s Gen 2", "Battery": "5000mAh", "Charging": "120W" },
    tags:          ["smartphone", "xiaomi", "redmi", "200mp"],
    rating:        4.5,
    review_count:  143,
  },
  {
    name:          "Canon EOS R50 Mirrorless Camera",
    description:   "A versatile mirrorless camera perfect for creators. 24.2MP APS-C sensor, 4K video, Dual Pixel CMOS AF II with subject tracking, and built-in Wi-Fi.",
    price:         310000,
    original_price:360000,
    category:      "electronics",
    category_name: "Electronics",
    brand:         "Canon",
    images:        [
      "https://i.ebayimg.com/images/g/umYAAOSwR5ZnyLmN/s-l1600.webp",
      "https://i.ebayimg.com/images/g/zWoAAeSwQ6Jpc6Fq/s-l1600.webp",
      "https://i.ebayimg.com/images/g/JVEAAOSw4HlnyLmC/s-l1600.webp",
      "https://i.ebayimg.com/images/g/epQAAOSwYyxnyLmG/s-l1600.webp",
      "https://i.ebayimg.com/images/g/9bYAAOSwtF5nyLmK/s-l1600.webp",
      "https://i.ebayimg.com/images/g/bXUAAOSwMNVnyLmD/s-l1600.webp",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         15,
    specs:         { "Sensor": "24.2MP APS-C CMOS", "Video": "4K 30fps", "AF": "Dual Pixel CMOS AF II", "Battery Life": "~390 shots", "Weight": "375g" },
    tags:          ["camera", "canon", "mirrorless", "photography"],
    rating:        4.6,
    review_count:  64,
  },
  {
    name:          "Apple Watch Series 9 GPS 45mm",
    description:   "The most advanced Apple Watch yet. Features S9 chip with double tap gesture, always-on Retina display, crash detection, and up to 18 hours battery.",
    price:         280000,
    original_price:null,
    category:      "electronics",
    category_name: "Electronics",
    brand:         "Apple",
    images:        [
      "https://i.ebayimg.com/images/g/oPIAAeSwLrZpdVJj/s-l1600.webp",
      "https://i.ebayimg.com/images/g/lmoAAeSw8UdpdVJj/s-l1600.webp",
      "https://i.ebayimg.com/images/g/UbYAAOSwO4ZlSM-m/s-l960.webp",
    ],
    badge:         "new",
    is_new:        true,
    is_best_seller:false,
    stock:         40,
    specs:         { "Chip": "S9 SiP", "Display": "Always-On Retina", "Case Size": "45mm", "Battery": "Up to 18 hours", "Water Resistance": "50 metres" },
    tags:          ["smartwatch", "apple", "wearable", "fitness"],
    rating:        4.8,
    review_count:  201,
  },
  {
    name:          "Dell XPS 15 Laptop Intel Core i7",
    description:   "A stunning 15.6\" OLED display, Intel Core i7-13700H, NVIDIA GeForce RTX 4060, 16GB RAM and 512GB SSD packed in a premium aluminium chassis.",
    price:         720000,
    original_price:850000,
    category:      "electronics",
    category_name: "Electronics",
    brand:         "Dell",
    images:        [
      "https://i.ebayimg.com/images/g/NvwAAeSwjC9pz5kK/s-l1600.webp",
      "https://i.ebayimg.com/images/g/LB8AAeSw9hFpz5kK/s-l1600.webp",
      "https://i.ebayimg.com/images/g/utYAAeSwtRBpz5kK/s-l1600.webp",
      "https://i.ebayimg.com/images/g/wb8AAeSwVklpz5kK/s-l1600.webp",
      "https://i.ebayimg.com/images/g/we8AAeSwDFxpz5kK/s-l1600.webp",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         10,
    specs:         { "CPU": "Intel Core i7-13700H", "GPU": "NVIDIA RTX 4060", "RAM": "16GB DDR5", "Storage": "512GB NVMe SSD", "Display": "15.6\" OLED Touch" },
    tags:          ["laptop", "dell", "xps", "gaming"],
    rating:        4.6,
    review_count:  88,
  },
  {
    name:          "DJI Mini 4 Pro Drone",
    description:   "Ultra-lightweight foldable drone under 249g. Shoots 4K/60fps HDR video, has 34-min flight time, omnidirectional obstacle sensing, and ActiveTrack 360.",
    price:         410000,
    original_price:460000,
    category:      "electronics",
    category_name: "Electronics",
    brand:         "DJI",
    images:        [
      "https://m.media-amazon.com/images/I/61CeeoQePzL._AC_SY300_SX300_QL70_FMwebp_.jpg",
      "https://m.media-amazon.com/images/I/51XZXhIeZ1L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61uhjPmmFFL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/81nUgCwviWL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/71ZLt4gJzvL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/813HA7Kh1VL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/413hj7JOmRL._AC_.jpg",
      "https://m.media-amazon.com/images/I/71O4LpQ-S6L._AC_SL1500_.jpg",
    ],
    badge:         "new",
    is_new:        true,
    is_best_seller:false,
    stock:         20,
    specs:         { "Weight": "249g", "Video": "4K/60fps HDR", "Flight Time": "34 minutes", "Range": "20km", "Obstacle Sensing": "Omnidirectional" },
    tags:          ["drone", "dji", "4k", "aerial"],
    rating:        4.7,
    review_count:  52,
  },

  // ── Fashion (10 products) ───────────────────────────────────────────────────
  {
    name:          "Nike Air Jordan 1 Retro High OG",
    description:   "The shoe that started it all. The Air Jordan 1 Retro High OG features premium leather upper, encapsulated Air-Sole unit, and classic Wings logo on the ankle collar.",
    price:         95000,
    original_price:115000,
    category:      "fashion",
    category_name: "Fashion",
    brand:         "Nike",
    images:        [
      "https://cdn-images.farfetch-contents.com/23/78/92/31/23789231_55071314_1000.jpg",
      "https://cdn-images.farfetch-contents.com/23/78/92/31/23789231_55071307_1000.jpg",
      "https://cdn-images.farfetch-contents.com/23/78/92/31/23789231_55071311_1000.jpg",
      "https://cdn-images.farfetch-contents.com/23/78/92/31/23789231_55071311_1000.jpg",
      "https://cdn-images.farfetch-contents.com/23/78/92/31/23789231_55071310_1000.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:true,
    stock:         35,
    specs:         { "Material": "Premium leather", "Sole": "Rubber", "Closure": "Lace-up", "Style": "High Top", "Available Sizes": "38-47" },
    tags:          ["sneakers", "nike", "jordan", "basketball"],
    rating:        4.9,
    review_count:  567,
  },
  {
    name:          "Adidas Originals Superstar Sneakers",
    description:   "Iconic shell-toe sneakers with a leather upper and the legendary 3-Stripes. A classic street style staple that goes with everything.",
    price:         55000,
    original_price:68000,
    category:      "fashion",
    category_name: "Fashion",
    brand:         "Adidas",
    images:        [
      "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/21b07d61e36742f2b6fa6091f3b97744_9366/ADIDAS_CARE_BEARS_SUPERSTAR_II_SHOES_Pink_KK4864_01_00_standard.jpg",
      "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/ddf1fc549a324b638cfae13cf6a5be98_9366/ADIDAS_CARE_BEARS_SUPERSTAR_II_SHOES_Pink_KK4864_14_hover_standard.jpg",
      "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/a68793303a1c4111ac575e40eb455f4f_9366/ADIDAS_CARE_BEARS_SUPERSTAR_II_SHOES_Pink_KK4864_02_standard.jpg",
      "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/406c0e4af31f4b488ec1a6469bc63302_9366/ADIDAS_CARE_BEARS_SUPERSTAR_II_SHOES_Pink_KK4864_03_standard.jpg",
      "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/3907ece5a14c4f999be443e84ef25900_9366/ADIDAS_CARE_BEARS_SUPERSTAR_II_SHOES_Pink_KK4864_04_standard.jpg",
      "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/a4d53f718d044fe5adb35f24e8444d37_9366/ADIDAS_CARE_BEARS_SUPERSTAR_II_SHOES_Pink_KK4864_05_standard.jpg",
      "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/5452cd6a3a334e3998f3c9ea756f70c5_9366/ADIDAS_CARE_BEARS_SUPERSTAR_II_SHOES_Pink_KK4864_06_standard.jpg",
      "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/4678d3a9317e413fb4cae962666334f5_9366/ADIDAS_CARE_BEARS_SUPERSTAR_II_SHOES_Pink_KK4864_09_standard.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:true,
    stock:         50,
    specs:         { "Upper": "Leather", "Sole": "Rubber", "Closure": "Lace-up", "Style": "Low Top", "Available Sizes": "36-48" },
    tags:          ["sneakers", "adidas", "originals", "classic"],
    rating:        4.7,
    review_count:  342,
  },
  {
    name:          "Zara Premium Linen Suit — Navy",
    description:   "Effortlessly sharp tailored suit in premium linen blend. Features a slim fit jacket with notch lapels, two-button front, and matching straight-leg trousers. Perfect for Nigerian weather.",
    price:         78000,
    original_price:null,
    category:      "fashion",
    category_name: "Fashion",
    brand:         "Zara",
    images:        [
      "https://static.zara.net/assets/public/198b/79dc/6e904d60856a/c0194bec5a97/04010901711-e1/04010901711-e1.jpg?ts=1782825370511&w=1430",
      "https://static.zara.net/assets/public/155f/6d93/6610417a8823/7a32d194c88c/04010901711-e2/04010901711-e2.jpg?ts=1782825370823&w=1430",
      "https://static.zara.net/assets/public/542f/954e/7bdc4f618b31/98aeeb9ffedb/04010901711-p/04010901711-p.jpg?ts=1783060795202&w=1430",
      "https://static.zara.net/assets/public/d5b3/1285/e30b4c968ac5/d0a6ff56b174/04010901711-a1/04010901711-a1.jpg?ts=1783060795227&w=1430",
      "https://static.zara.net/assets/public/7905/02cb/b10242609d4a/ac148136024b/04010901711-a2/04010901711-a2.jpg?ts=1783060794799&w=1430",
      "https://static.zara.net/assets/public/df31/ae9e/adf5480a8aad/119aaad9ae27/04010901711-a3/04010901711-a3.jpg?ts=1783060794721&w=1430",
    ],
    badge:         "new",
    is_new:        true,
    is_best_seller:false,
    stock:         25,
    specs:         { "Material": "55% Linen, 45% Viscose", "Fit": "Slim", "Care": "Dry clean only", "Available Sizes": "S, M, L, XL, XXL" },
    tags:          ["suit", "formal", "linen", "zara", "men"],
    rating:        4.5,
    review_count:  48,
  },
  {
    name:          "Gucci GG Marmont Mini Bag",
    description:   "Crafted in matelassé leather with the iconic Double G hardware. A timeless design with a distinctive chevron stitch and signature GG turnlock. Includes adjustable shoulder strap.",
    price:         380000,
    original_price:430000,
    category:      "fashion",
    category_name: "Fashion",
    brand:         "Gucci",
    images:        [
      "https://i.ebayimg.com/images/g/6AsAAeSw1tJqRwUz/s-l1600.webp",
      "https://i.ebayimg.com/images/g/9YkAAeSwk4BqRwUU/s-l1600.webp",
      "https://i.ebayimg.com/images/g/72IAAeSw0VlqRwUZ/s-l1600.webp",
      "https://i.ebayimg.com/images/g/AbwAAeSwyN1qRwUh/s-l1600.webp",
      "https://i.ebayimg.com/images/g/cgUAAeSwih1qRwUn/s-l1600.webp",
      "https://i.ebayimg.com/images/g/7ewAAeSwBoFqRwTt/s-l1600.webp",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         8,
    specs:         { "Material": "Matelassé leather", "Hardware": "Aged gold-toned", "Dimensions": "18.5 x 13 x 6.5 cm", "Strap Drop": "Adjustable 30-70 cm" },
    tags:          ["bag", "gucci", "luxury", "handbag", "women"],
    rating:        4.8,
    review_count:  93,
  },
  {
    name:          "H&M Oversized Puffer Jacket — Black",
    description:   "Warm and stylish oversized puffer jacket with a stand-up collar, zip front, and side pockets. Water-repellent finish with recycled polyester filling.",
    price:         32000,
    original_price:42000,
    category:      "fashion",
    category_name: "Fashion",
    brand:         "H&M",
    images:        [
      "https://image.hm.com/assets/hm/b8/1f/b81fc67bd4f230280f262a1926c78e6707e64cbe.jpg?imwidth=2160",
      "https://image.hm.com/assets/hm/b2/c1/b2c19ded5431a60ac4993267a576a0baa8c286f3.jpg?imwidth=2160",
      "https://image.hm.com/assets/hm/ed/80/ed8083bd98d19d642d119c783b06470d0dd92e55.jpg?imwidth=2160",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         70,
    specs:         { "Material": "100% Recycled Polyester", "Filling": "Recycled Polyester", "Fit": "Oversized", "Available Sizes": "XS–XXL", "Colour": "Black" },
    tags:          ["jacket", "winter", "puffer", "hm", "women"],
    rating:        4.3,
    review_count:  215,
  },
  {
    name:          "Levi's 501 Original Jeans — Dark Indigo",
    description:   "The jean that started it all. Levi's 501 Original Jeans feature a straight leg, button fly, and signature Levi's leather patch. Made with cotton stretch for added comfort.",
    price:         28500,
    original_price:35000,
    category:      "fashion",
    category_name: "Fashion",
    brand:         "Levi's",
    images:        [
      "https://levi.co.th/cdn/shop/files/levis-mens-501-original-jeans-005011484_1_ON_FV_1456x1600_crop_center.progressive.jpg?v=1713350665",
      "https://levi.co.th/cdn/shop/files/levis-mens-501-original-jeans-005011484_3_ON_SV_1456x1600_crop_center.progressive.jpg?v=1713350665",
      "https://levi.co.th/cdn/shop/files/levis-mens-501-original-jeans-005011484_3_ON_SV_1456x1600_crop_center.progressive.jpg?v=1713350665",
      "https://levi.co.th/cdn/shop/files/levis-mens-501-original-jeans-005011484_2_ON_BV_1456x1600_crop_center.progressive.jpg?v=1713353814",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:true,
    stock:         90,
    specs:         { "Material": "99% Cotton, 1% Elastane", "Fit": "Straight", "Rise": "High Rise", "Closure": "Button Fly", "Available Sizes": "28–38" },
    tags:          ["jeans", "denim", "levis", "men", "classic"],
    rating:        4.6,
    review_count:  388,
  },
  {
    name:          "New Balance 574 Classic Trainers",
    description:   "One of New Balance's most iconic silhouettes, the 574 features an encap midsole for premium cushioning, suede and mesh upper, and reflective NB logo.",
    price:         48000,
    original_price:58000,
    category:      "fashion",
    category_name: "Fashion",
    brand:         "New Balance",
    images:        [
      "https://cdn-images.farfetch-contents.com/20/20/64/43/20206443_50082436_1000.jpg",
      "https://cdn-images.farfetch-contents.com/20/20/64/43/20206443_50082433_1000.jpg",
      "https://cdn-images.farfetch-contents.com/20/20/64/43/20206443_50082431_1000.jpg",
      "https://cdn-images.farfetch-contents.com/20/20/64/43/20206443_50082435_1000.jpg",
      "https://cdn-images.farfetch-contents.com/20/20/64/43/20206443_50082440_1000.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         42,
    specs:         { "Upper": "Suede/Mesh", "Midsole": "ENCAP", "Closure": "Lace-up", "Style": "Low Top", "Available Sizes": "36-47" },
    tags:          ["sneakers", "new-balance", "574", "running"],
    rating:        4.5,
    review_count:  176,
  },
  {
    name:          "Ralph Lauren Polo Classic Fit Shirt — White",
    description:   "The iconic Polo Ralph Lauren shirt in classic fit. Features the signature embroidered pony logo, soft cotton piqué fabric, and ribbed collar and cuffs.",
    price:         22000,
    original_price:28000,
    category:      "fashion",
    category_name: "Fashion",
    brand:         "Ralph Lauren",
    images:        [
      "https://dtcralphlauren.scene7.com/is/image/PoloGSI/s7-1352637_alternate10?$rl_4x5_pdp$",
      "https://dtcralphlauren.scene7.com/is/image/PoloGSI/s7-1352637_alternate5?$rl_4x5_zoom$",
      "https://dtcralphlauren.scene7.com/is/image/PoloGSI/s7-1352637_lifestyle?$rl_4x5_zoom$",
      "https://dtcralphlauren.scene7.com/is/image/PoloGSI/s7-1352637_alternate1?$rl_4x5_zoom$",
      "https://dtcralphlauren.scene7.com/is/image/PoloGSI/s7-1352637_alternate3?$rl_4x5_zoom$",
      "https://dtcralphlauren.scene7.com/is/image/PoloGSI/s7-1352637_alternate4?$rl_4x5_zoom$",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         80,
    specs:         { "Material": "100% Cotton piqué", "Fit": "Classic", "Collar": "Ribbed polo collar", "Available Sizes": "S, M, L, XL, XXL, XXXL" },
    tags:          ["polo", "ralph-lauren", "shirt", "casual"],
    rating:        4.4,
    review_count:  241,
  },
  {
    name:          "Zara Satin Slip Midi Dress — Cream",
    description:   "Elegant slip midi dress in lustrous satin. Features adjustable spaghetti straps, a V-neckline, and a fluid silhouette. Versatile enough for daytime or evening events.",
    price:         19500,
    original_price:26000,
    category:      "fashion",
    category_name: "Fashion",
    brand:         "Zara",
    images:        [
      "https://i.ebayimg.com/images/g/IVkAAeSwk8FqSDIw/s-l1600.webp",
      "https://i.ebayimg.com/images/g/erAAAeSwixZqSC7Q/s-l1600.webp",
      "https://i.ebayimg.com/images/g/E4IAAeSwB1xqSC7z/s-l1600.webp",
      "https://i.ebayimg.com/images/g/-lMAAeSw40VqSC7b/s-l1600.webp",
      "https://i.ebayimg.com/images/g/Y34AAeSwrHNqSC7h/s-l1600.webp",
      "https://i.ebayimg.com/images/g/btEAAeSwENBqSC7l/s-l1600.webp",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         55,
    specs:         { "Material": "100% Polyester satin", "Fit": "Slim", "Length": "Midi", "Neckline": "V-neck", "Available Sizes": "XS–XL" },
    tags:          ["dress", "satin", "women", "zara", "formal"],
    rating:        4.6,
    review_count:  132,
  },
  {
    name:          "Hermès Belt H Buckle 32mm",
    description:   "The iconic Hermès H Belt in Togo calfskin with palladium-finish H buckle. A timeless investment accessory handcrafted in France.",
    price:         210000,
    original_price:null,
    category:      "fashion",
    category_name: "Fashion",
    brand:         "Hermès",
    images:        [
      "https://assets.hermes.com/is/image/hermesproduct/h-belt-buckle-reversible-leather-strap-32mm--beltkits-32-011822UAAE_composite_3-064544CM2M_composite_3-0-0-800-800_g.jpg",
      "https://assets.hermes.com/is/image/hermesproduct/h-belt-buckle-reversible-leather-strap-32mm--beltkits-32-011822UAAE_composite_4-064544CM2M_composite_3-0-0-800-800_g.jpg",
      "https://assets.hermes.com/is/image/hermesproduct/h-belt-buckle-reversible-leather-strap-32mm--064544CM2M-worn-2-0-0-800-800_g.jpg",
    ],
    badge:         "hot",
    is_new:        false,
    is_best_seller:false,
    stock:         5,
    specs:         { "Material": "Togo calfskin", "Buckle": "Palladium-finish H", "Width": "32mm", "Origin": "France", "Available Sizes": "70-110cm" },
    tags:          ["belt", "hermes", "luxury", "accessories"],
    rating:        4.9,
    review_count:  37,
  },

  // ── Beauty (8 products) ─────────────────────────────────────────────────────
  {
    name:          "Fenty Beauty Pro Filt'r Soft Matte Foundation",
    description:   "Rihanna's iconic foundation with 50 shades built for all skin types. Oil-free formula provides 24-hour longwear coverage with a soft-matte finish. Sweat and humidity resistant.",
    price:         18500,
    original_price:22000,
    category:      "beauty",
    category_name: "Beauty",
    brand:         "Fenty Beauty",
    images:        [
      "https://www.essenza.ng/cdn/shop/products/816657022834_1.jpg?v=1666344903&width=500",
      "https://www.essenza.ng/cdn/shop/products/816657022865_3.jpg?v=1666344903&width=500",
      "https://www.essenza.ng/cdn/shop/products/816657022834_5.jpg?v=1666344903&width=500",
      "https://www.essenza.ng/cdn/shop/products/816657022865_1.jpg?v=1666344903&width=500",
      "https://www.essenza.ng/cdn/shop/products/816657022834_2.jpg?v=1666344903&width=500",
      "https://www.essenza.ng/cdn/shop/products/816657022865_5.jpg?v=1666344903&width=500",
      "https://www.essenza.ng/cdn/shop/products/816657022827_1.jpg?v=1652434045&width=500",
      "https://www.essenza.ng/cdn/shop/products/816657022865_2.jpg?v=1666344903&width=500",
      "https://www.essenza.ng/cdn/shop/products/816657022827_5.jpg?v=1666344903&width=500",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:true,
    stock:         120,
    specs:         { "Coverage": "Medium-full, buildable", "Finish": "Soft matte", "Formula": "Oil-free", "Shades": "50", "Size": "32ml" },
    tags:          ["foundation", "fenty", "makeup", "skincare"],
    rating:        4.8,
    review_count:  729,
  },
  {
    name:          "Dyson Airwrap Multi-Styler Complete",
    description:   "Style, dry, and curl simultaneously with the Dyson Airwrap. Uses Coanda airflow to attract and wrap hair for volume, waves, or curls. Includes 6 attachments for all hair types.",
    price:         295000,
    original_price:330000,
    category:      "beauty",
    category_name: "Beauty",
    brand:         "Dyson",
    images:        [
      "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/images/products/primary/123668-01.png?cropPathE=mobile&fit=stretch,1&wid=640",
      "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/products/hair-care/2025-colorways/ceramic-pink/galleries/airwrap/AW_COM_Ceramic-Pink_Enhanced_SW_2.jpg?cropPathE=mobile&fit=stretch,1&wid=640",
      "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/products/hair-care/dyson-airwrapid/PDPs/strawberry-bronze-blush-pink/straight-wavy/Gallery/with-copy/308F_Strawberry_Gallery_T1T2_With%20copy_07.jpg?cropPathE=mobile&fit=stretch,1&wid=640",
      "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/products/hair-care/dyson-airwrapid/PDPs/usa-alt-galley/SW1.png?cropPathE=mobile&fit=stretch,1&wid=640",
      "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/products/hair-care/dyson-airwrapid/PDPs/usa-alt-galley/US%20ALT%207.png?cropPathE=mobile&fit=stretch,1&wid=640",
      "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/products/hair-care/dyson-airwrapid/PDPs/strawberry-bronze-blush-pink/straight-wavy/Gallery/with-copy/308F_Strawberry_Gallery_T1T2_With%20copy_04.jpg?cropPathE=mobile&fit=stretch,1&wid=640",
    ],
    videos:        [
      "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:true,
    stock:         18,
    specs:         { "Attachments": "6 included", "Voltage": "110-240V", "Weight": "1.35kg", "Heat Settings": "3 temperatures", "Cord Length": "2.7m" },
    tags:          ["hair", "dyson", "styling", "curls"],
    rating:        4.7,
    review_count:  284,
  },
  {
    name:          "Charlotte Tilbury Flawless Filter Primer",
    description:   "A multi-purpose complexion booster that blurs pores, adds radiance, and primes skin for makeup. Buildable formula from sheer to medium coverage with SPF 25.",
    price:         16800,
    original_price:null,
    category:      "beauty",
    category_name: "Beauty",
    brand:         "Charlotte Tilbury",
    images:        [
      "https://images.ctfassets.net/wlke2cbybljx/2UYfjx8v5iYehpDx7Qd2VP/cefd94b4c43ae47757c777a383c6b18d/HFFMINI-4.5-BESTSELLER-PDP.png?w=660&h=660&fit=fill&q=80&fm=webp",
      "https://images.ctfassets.net/wlke2cbybljx/7gdtwGZzSi9MLkWxtw25sD/469d509d31cc2b712690f72a411cf223/HFF4.5-B_A.jpg?w=660&h=660&fit=fill&q=80&fm=webp",
      "https://images.ctfassets.net/wlke2cbybljx/4Eeb8HIAwZqFAPx1i5l07c/cf3e4b425e03ec8d3aed61c6dbb5eb65/HFF_Benefit_On_Skin_1000x1000__1_.jpg?w=660&h=660&fit=fill&q=80&fm=webp",
      "https://images.ctfassets.net/wlke2cbybljx/5tfXvSqDhV7cd1NMr4TvHt/fa1891561370df1612fd213db61b5a74/Hollywood_Flawless_Filter_Ingredients.jpg?w=660&h=660&fit=fill&q=80&fm=webp",
      "https://images.ctfassets.net/wlke2cbybljx/6gQBflQTrRkQJQo3h89mK5/af19af647a6215c0c8a124bbdf6c5fe4/Hollywood_Flawless_Filter_Texture.jpg?w=660&h=660&fit=fill&q=80&fm=webp",
      "https://images.ctfassets.net/wlke2cbybljx/4vDnX0WN8wmRfayx3jTmsF/e099aff2861a7b34b350ecd6fbbbe156/Screenshot_2023-08-15_at_10.17.46.png?w=660&h=660&fit=fill&q=80&fm=webp",
      "https://images.ctfassets.net/wlke2cbybljx/3oywhaPlJ2hnaJPZ5QGl70/b9568eb5e883562390282e23fcd57401/MINI_HFF.png?w=660&h=660&fit=fill&q=80&fm=webp",
    ],
    badge:         "new",
    is_new:        true,
    is_best_seller:true,
    stock:         75,
    specs:         { "SPF": "25", "Coverage": "Sheer to medium", "Finish": "Glowing", "Size": "30ml", "Skin Type": "All skin types" },
    tags:          ["primer", "charlotte-tilbury", "makeup", "radiance"],
    rating:        4.6,
    review_count:  193,
  },
  {
    name:          "The Ordinary Niacinamide 10% + Zinc 1%",
    description:   "High-strength vitamin and mineral blemish formula. Reduces the appearance of skin blemishes and congestion. A water-based serum that is ideal for all skin types.",
    price:         4500,
    original_price:5800,
    category:      "beauty",
    category_name: "Beauty",
    brand:         "The Ordinary",
    images:        [
      "https://rhemabeautyshop.com/wp-content/uploads/2023/04/12243648-8334901838633417-600x600-1.jpeg",
      "https://m.media-amazon.com/images/I/81TtdjfUduL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71gT5-W8WEL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71Y6JkQW6dL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71Q0SoLNrzL._SX522_.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:true,
    stock:         200,
    specs:         { "Key Ingredients": "Niacinamide 10%, Zinc 1%", "Skin Type": "All", "Size": "30ml", "Formula": "Water-based", "pH": "5.5-6.5" },
    tags:          ["serum", "the-ordinary", "skincare", "niacinamide"],
    rating:        4.7,
    review_count:  1203,
  },
  {
    name:          "MAC Studio Fix Fluid Foundation SPF15",
    description:   "Beloved oil-controlling foundation with buildable medium-to-full coverage and a natural matte finish. Available in 60 shades. Lasts up to 24 hours.",
    price:         14500,
    original_price:17000,
    category:      "beauty",
    category_name: "Beauty",
    brand:         "MAC",
    images:        [
      "https://sdcdn.io/mc/mac_sku_SRN001_3000x3000_0S.png?height=700px&width=700px",
      "https://sdcdn.io/mc/mac_sku_SRN001_3000x3000_2.png?height=700px&width=700px",
      "https://sdcdn.io/mc/mac_sku_SRN001_3000x3000_6.png?height=700px&width=700px",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         95,
    specs:         { "SPF": "15", "Coverage": "Medium-to-full", "Finish": "Natural matte", "Shades": "60+", "Size": "30ml" },
    tags:          ["foundation", "mac", "makeup", "matte"],
    rating:        4.5,
    review_count:  487,
  },
  {
    name:          "Neutrogena Hydro Boost Water Gel",
    description:   "Lightweight gel moisturiser that instantly quenches dry skin and keeps it hydrated for 48 hours. Contains Hyaluronic Acid to lock in moisture. Oil-free and non-comedogenic.",
    price:         6500,
    original_price:8200,
    category:      "beauty",
    category_name: "Beauty",
    brand:         "Neutrogena",
    images:        [
      "https://images.ctfassets.net/3zfcttr0ztpr/3TfmeqVtWAAtF8LobCI3ss/c88eeb16274d0134ae5062c8a6cd2b5f/NTG_USA_US_70501110478_681104748_HB_Hyaluronic_Acid_Water_Gel_Signature_1p7oz_00000.webp?w=1080&fm=avif&q=80",
      "https://images.ctfassets.net/3zfcttr0ztpr/38M2i3fffoHXtO2TtW6BN0/387607ebc52804a93fbe91aee4d76918/NA_US_NTG_Tate_HydroBoost_WaterGel_1.7floz_KillerClaimAndSkin_ATF2_Amazon_3000x3000_v2.webp?w=1080&fm=avif&q=80",
      "http://images.ctfassets.net/3zfcttr0ztpr/1yMI8CUsLgGlAJ4J6h5yeQ/55d299ad65f273092909bef462ac9fff/NA_US_NTG_HydroBoost_WaterGel_1.7floz_KeyBenefit_ATF3_Amazon_3000x3000.webp?w=1080&fm=avif&q=80",
      "https://images.ctfassets.net/3zfcttr0ztpr/3QZLk9rzhRVLgJNw7zx0SZ/0483fc11e3d830ca0c36ef56df9c8209/NA_US_NTG_HydroBoost_WaterGel_1.7floz_IngredientsAndScience_ATF4_Amazon_3000x3000.webp?w=1080&fm=avif&q=80",
      "https://images.ctfassets.net/3zfcttr0ztpr/4M3URIzrGwxHTPKEQYHNTH/c6cd5d27fc28c2f3f9b0a0fd368a4f12/NA_US_NTG_HydroBoost_WaterGel_1.7floz_HUT_ATF5_Amazon_3000x3000.webp?w=1080&fm=avif&q=80",
      "https://images.ctfassets.net/3zfcttr0ztpr/3GOFEzxVfeZvDfFRwHXWos/3b2680d2ebb1a123a1e6117e67dc3dc2/AboveTheFold_Regimen1_HB_WaterGel_HydratingGelCleanser.webp?w=1080&fm=avif&q=80",
      "https://images.ctfassets.net/3zfcttr0ztpr/1GMBupKZKwhxKUorgTMQip/c33da4d022359ca03ffdea4a36a37d4a/NA_US_NTG_HydroBoost_WaterGel_1.7floz_SafetyFormula_ATF6_Amazon_3000x3000.webp?w=1080&fm=avif&q=80",
      "https://images.ctfassets.net/3zfcttr0ztpr/50PiDQ6osxc8EXG9FIjJJK/bdddff6358fba009885a87158bb362b5/NTG_USA_US_70501110478_681104748_HB_Hyaluronic_Acid_Water_Gel_Signature_1p7oz_00180.webp?w=1080&fm=avif&q=80",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:true,
    stock:         150,
    specs:         { "Key Ingredient": "Hyaluronic Acid", "Hydration": "48 hours", "Formula": "Oil-free, non-comedogenic", "Skin Type": "All, especially dry", "Size": "50ml" },
    tags:          ["moisturiser", "neutrogena", "skincare", "hydration"],
    rating:        4.6,
    review_count:  621,
  },
  {
    name:          "Victoria's Secret Bombshell Eau de Parfum",
    description:   "The iconic Bombshell fragrance — a fresh floral bouquet of purple passion fruit, Shangri-la peony, and vanilla orchid. Long-lasting and irresistibly feminine.",
    price:         22000,
    original_price:28500,
    category:      "beauty",
    category_name: "Beauty",
    brand:         "Victoria's Secret",
    images:        [
      "https://www.victoriassecret.com/p/1520x2026/png/zz/26/04/03/02/112756207100_OM_B.jpg",
      "https://www.victoriassecret.com/p/1520x2026/png/zz/26/03/20/03/112756207100_alt.jpg",
      "https://www.victoriassecret.com/p/1520x2026/png/zz/26/04/03/02/112756207100_OM_F.jpg",
      "https://www.victoriassecret.com/p/1520x2026/png/zz/26/03/20/03/112756207100_alt3.jpg",
      "https://www.victoriassecret.com/p/1520x2026/png/zz/26/04/06/04/112756207100_alt2.jpg",
      "https://www.victoriassecret.com/p/1520x2026/png/zz/26/05/11/03/112756207100_alt6.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         65,
    specs:         { "Size": "100ml", "Concentration": "Eau de Parfum", "Top Notes": "Purple Passion Fruit", "Heart Notes": "Peony", "Base Notes": "Vanilla Orchid" },
    tags:          ["perfume", "fragrance", "victoria-secret", "women"],
    rating:        4.4,
    review_count:  328,
  },
  {
    name:          "OGX Biotin & Collagen Shampoo & Conditioner Set",
    description:   "Volumising shampoo and conditioner set infused with biotin and collagen. Helps thicken hair strands while adding body and fullness. Sulfate-free and paraben-free.",
    price:         8900,
    original_price:11500,
    category:      "beauty",
    category_name: "Beauty",
    brand:         "OGX",
    images:        [
      "https://ip.prod.freshop.retail.ncrcloud.com/resize?url=https://images.freshop.ncrcloud.com/00022796916709/e9040d784a367a237f4ea26782ed9705_large.png&width=512&type=webp&quality=80",
      "https://ip.prod.freshop.retail.ncrcloud.com/resize?url=https://images.freshop.ncrcloud.com/00022796916709/549225b32574647540985077a0800acf_large.png&width=512&type=webp&quality=80",
      "https://ip.prod.freshop.retail.ncrcloud.com/resize?url=https://images.freshop.ncrcloud.com/00022796916709/5ba424d355c42230ef44122a5fdd9efa_large.png&width=512&type=webp&quality=80",
      "https://ip.prod.freshop.retail.ncrcloud.com/resize?url=https://images.freshop.ncrcloud.com/00022796916709/b9a961c2917650a598247c12a74a4003_large.png&width=512&type=webp&quality=80",
      "https://ip.prod.freshop.retail.ncrcloud.com/resize?url=https://images.freshop.ncrcloud.com/00022796916709/78c4982d03025b018b16a3c3d6999944_large.png&width=512&type=webp&quality=80",
      "https://ip.prod.freshop.retail.ncrcloud.com/resize?url=https://images.freshop.ncrcloud.com/00022796916709/7978978e1320bb6581db9a6ef1e37b8f_large.png&width=512&type=webp&quality=80",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         110,
    specs:         { "Key Ingredients": "Biotin, Collagen", "Size": "385ml each", "Sulfate-Free": "Yes", "Paraben-Free": "Yes", "Hair Type": "All hair types" },
    tags:          ["shampoo", "conditioner", "hair", "ogx", "biotin"],
    rating:        4.4,
    review_count:  245,
  },

  // ── Home & Living (6 products) ──────────────────────────────────────────────
  {
    name:          "Dyson V15 Detect Cordless Vacuum",
    description:   "Dyson's most powerful cordless vacuum with laser dust detection technology. Green diode laser reveals invisible dust, while LCD screen shows particle counts in real time. 60 minutes runtime.",
    price:         320000,
    original_price:375000,
    category:      "home",
    category_name: "Home & Living",
    brand:         "Dyson",
    images:        [
      "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/us/floorcare/npd-2023/v15/08.jpg?cropPathE=desktop&fit=stretch,1&wid=1152",
      "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/images/products/primary/626417-01.png?cropPathE=desktop&fit=stretch,1&wid=1152",
      "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/us/floorcare/npd-2023/v15/02.jpg?cropPathE=desktop&fit=stretch,1&wid=1152",
      "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/us/floorcare/npd-2023/v15/07.jpg?cropPathE=desktop&fit=stretch,1&wid=1152",
      "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/us/floorcare/npd-2023/v15/01.jpg?cropPathE=desktop&fit=stretch,1&wid=1152",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:true,
    stock:         22,
    specs:         { "Suction": "230 AW", "Battery": "Up to 60 min", "Bin Volume": "0.77L", "Weight": "3.1kg", "Filter": "HEPA" },
    tags:          ["vacuum", "dyson", "cordless", "cleaning"],
    rating:        4.7,
    review_count:  156,
  },
  {
    name:          "Instant Pot Duo 7-in-1 Electric Pressure Cooker 6Qt",
    description:   "The #1 best-selling multi-cooker. Pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker, and warmer all in one. Cooks up to 70% faster.",
    price:         38000,
    original_price:48000,
    category:      "home",
    category_name: "Home & Living",
    brand:         "Instant Pot",
    images:        [
      "https://m.media-amazon.com/images/I/61WZ8UkkReL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81zUcuoZzoL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/818BFBGcmJL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81jn3nLAsAL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81gbx1yK7pL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71EEazCVODL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71C4Z3ERG7L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71TLfJMT1XL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81SqTxkgiQL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71Eo8ppHJLL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/918QQ-mSWJL._AC_SL1500_.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:true,
    stock:         45,
    specs:         { "Capacity": "6 Quarts", "Functions": "7-in-1", "Programmes": "13 built-in", "Power": "1000W", "Safety": "10 safety features" },
    tags:          ["kitchen", "pressure-cooker", "instant-pot", "cooking"],
    rating:        4.8,
    review_count:  934,
  },
  {
    name:          "IKEA KALLAX Shelf Unit — White",
    description:   "Versatile shelf unit that can be used free-standing or mounted on the wall. Compatible with KALLAX inserts for customised storage. Each compartment holds up to 13kg.",
    price:         42000,
    original_price:null,
    category:      "home",
    category_name: "Home & Living",
    brand:         "IKEA",
    images:        [
      "https://www.ikea.com/us/en/images/products/kallax-shelf-unit-white__0644757_pe702939_s5.jpg?f=xl",
      "https://www.ikea.com/us/en/images/products/kallax-shelf-unit-white__1084790_pe859876_s5.jpg?f=xl",
      "https://www.ikea.com/us/en/images/products/kallax-shelf-unit-white__1084796_pe859882_s5.jpg?f=xl",
      "https://www.ikea.com/us/en/images/products/kallax-shelf-unit-white__1051325_pe845148_s5.jpg?f=xl",
      "https://www.ikea.com/us/en/images/products/kallax-shelf-unit-white__1099106_pe865602_s5.jpg?f=xl",
      "https://www.ikea.com/us/en/images/products/kallax-shelf-unit-white__1215327_pe911964_s5.jpg?f=xl",
    ],
    badge:         null,
    is_new:        false,
    is_best_seller:false,
    stock:         30,
    specs:         { "Dimensions": "77x77x39cm", "Material": "Particleboard, Fiberboard", "Colour": "White", "Load Capacity": "13kg/shelf", "Assembly": "Required" },
    tags:          ["shelving", "ikea", "storage", "furniture"],
    rating:        4.3,
    review_count:  287,
  },
  {
    name:          "Nespresso Vertuo Next Coffee Machine",
    description:   "Versatile coffee machine that brews 5 cup sizes from espresso to alto. Uses Centrifusion extraction technology for perfect crema every time. Includes welcome pack.",
    price:         68000,
    original_price:82000,
    category:      "home",
    category_name: "Home & Living",
    brand:         "Nespresso",
    images:        [
      "https://i.ebayimg.com/images/g/1W8AAOSw0aBkW306/s-l1600.webp",
      "https://i.ebayimg.com/images/g/tjIAAOSwEVZkW306/s-l1600.webp",
      "https://i.ebayimg.com/images/g/3BwAAOSwzUdkW306/s-l1600.webp",
      "https://i.ebayimg.com/images/g/N7gAAOSw4c9kW307/s-l1600.webp",
      "https://i.ebayimg.com/images/g/DWMAAOSw3GJkW307/s-l1600.webp",
      "https://i.ebayimg.com/images/g/AKoAAOSwsR5kW306/s-l1600.webp",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         35,
    specs:         { "Cup Sizes": "5 (40ml–414ml)", "Extraction": "Centrifusion", "Water Tank": "1.1L", "Heat Up Time": "30 seconds", "Connectivity": "Bluetooth" },
    tags:          ["coffee", "nespresso", "kitchen", "espresso"],
    rating:        4.5,
    review_count:  198,
  },
  {
    name:          "Philips Hue Starter Kit — White & Colour",
    description:   "Smart lighting starter kit with 3 E27 colour bulbs and Hue Bridge. Control 16 million colours via app or voice. Compatible with Alexa, Google Assistant, and Siri.",
    price:         55000,
    original_price:65000,
    category:      "home",
    category_name: "Home & Living",
    brand:         "Philips Hue",
    images:        [
      "https://m.media-amazon.com/images/I/71a+TRWuUnL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51zNmGTZdmL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51XssvlGuaL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61+2MU5efdL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/711hWt4xf0L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/715RAB2nv8L._AC_SL1500_.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         40,
    specs:         { "Bulbs Included": "3x E27 9W", "Colours": "16 million", "Connectivity": "Zigbee, Bluetooth", "Bridge": "Included", "Voice Control": "Alexa, Google, Siri" },
    tags:          ["smart-home", "lighting", "philips", "hue"],
    rating:        4.6,
    review_count:  312,
  },
  {
    name:          "Cuisinart Air Fryer Toaster Oven",
    description:   "3-in-1 air fryer, toaster oven, and broiler in one compact unit. Air fry with up to 98% less fat. Fits up to a 9\" pizza and holds 6 slices of toast.",
    price:         44500,
    original_price:55000,
    category:      "home",
    category_name: "Home & Living",
    brand:         "Cuisinart",
    images:        [
      "https://m.media-amazon.com/images/I/71UIRKGLtYL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81l0Sba9+SL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71d4KUYtl8L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71d4KUYtl8L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61dHGRfVbRL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61h1cXtkW2L._AC_SX679_.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         28,
    specs:         { "Functions": "3-in-1", "Capacity": "6-slice / 9\" pizza", "Power": "1800W", "Temperature Range": "60°C–230°C", "Accessories": "Air fry basket, baking pan, wire rack" },
    tags:          ["air-fryer", "kitchen", "cuisinart", "oven"],
    rating:        4.4,
    review_count:  187,
  },

  // ── Sports (5 products) ─────────────────────────────────────────────────────
  {
    name:          "Peloton Bike+ Stationary Exercise Bike",
    description:   "The ultimate home cycling experience. Auto-resistance, 24\" HD touchscreen, live and on-demand classes. Swivels for floor workouts. Includes shoe clips and weights.",
    price:         680000,
    original_price:780000,
    category:      "sports",
    category_name: "Sports",
    brand:         "Peloton",
    images:        [
      "https://m.media-amazon.com/images/I/61-WA+e9yaL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71rR5Bjl6BL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/714cW8jGqGL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71D+82CDmlL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81QRIf+rOWL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61eNAt4d91L._AC_SX679_.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         6,
    specs:         { "Screen": "24\" HD Touchscreen", "Resistance": "Auto, 100 levels", "Max User Weight": "136kg", "Connectivity": "Wi-Fi, Bluetooth", "Warranty": "1 year" },
    tags:          ["fitness", "cycling", "peloton", "indoor"],
    rating:        4.7,
    review_count:  89,
  },
  {
    name:          "Wilson Evolution Basketball",
    description:   "The #1 selling indoor basketball. Features patented Cushion Core Technology and lining channels for consistent feel. Composite leather cover for superior grip.",
    price:         18500,
    original_price:22000,
    category:      "sports",
    category_name: "Sports",
    brand:         "Wilson",
    images:        [
      "https://m.media-amazon.com/images/I/818bVxYc15L._AC_SY300_SX300_QL70_FMwebp_.jpg",
      "https://m.media-amazon.com/images/I/810bZRn10UL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/819hY6qLC0L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81ZZIieVuZL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81KItLwRgKL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81nOIYld2lL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71Ns6bLJ8wL._AC_SL1500_.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:true,
    stock:         80,
    specs:         { "Size": "7 (Official)", "Material": "Composite leather", "Surface": "Indoor", "Inflation": "8 PSI", "Circumference": "75-76cm" },
    tags:          ["basketball", "wilson", "sports", "indoor"],
    rating:        4.8,
    review_count:  412,
  },
  {
    name:          "Garmin Forerunner 265 GPS Running Watch",
    description:   "Advanced GPS running watch with AMOLED display, training readiness score, daily suggested workouts, and HRV status. Tracks over 30 sports activities.",
    price:         195000,
    original_price:230000,
    category:      "sports",
    category_name: "Sports",
    brand:         "Garmin",
    images:        [
      "https://m.media-amazon.com/images/I/71rp-pRCpRL._AC_SY300_SX300_QL70_FMwebp_.jpg",
      "https://m.media-amazon.com/images/I/71uTyOgkTpL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/71uvBtKWTEL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/61w7QyEUxxL._AC_SX466_.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         25,
    specs:         { "Display": "AMOLED 1.3\"", "GPS": "GPS/GLONASS/Galileo", "Battery": "Up to 15 days", "Water Rating": "5ATM", "Sports Profiles": "30+" },
    tags:          ["smartwatch", "garmin", "running", "gps", "fitness"],
    rating:        4.7,
    review_count:  134,
  },
  {
    name:          "Bowflex SelectTech 552 Adjustable Dumbbells (Pair)",
    description:   "Replace 15 sets of weights with one pair. Adjust from 2.3kg to 23.6kg in 2.3kg increments with a simple dial. Keeps your home gym organised and clutter-free.",
    price:         120000,
    original_price:145000,
    category:      "sports",
    category_name: "Sports",
    brand:         "Bowflex",
    images:        [
      "https://m.media-amazon.com/images/I/71bdxVC7-0L._AC_SY300_SX300_QL70_FMwebp_.jpg",
      "https://m.media-amazon.com/images/I/71x6ls+CzoL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81piynHrTAL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81zgZ3teG9L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71aVOmJYvEL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81El26nVJOL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/7141NwIm+GL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/713zdMJKDLL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61t8BI9NGDL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61wHhmnFPGL._AC_SL1500_.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         18,
    specs:         { "Weight Range": "2.3kg – 23.6kg", "Increments": "2.3kg", "Replaces": "15 pairs of dumbbells", "Material": "Steel, rubber", "Warranty": "2 years" },
    tags:          ["dumbbells", "weights", "fitness", "bowflex", "home-gym"],
    rating:        4.7,
    review_count:  278,
  },
  {
    name:          "Adidas Predator Edge+ Firm Ground Boots",
    description:   "Elite football boots with Demonskin coating for maximum ball manipulation. Control Frame outsole for explosive acceleration and superior stability on firm ground.",
    price:         88000,
    original_price:110000,
    category:      "sports",
    category_name: "Sports",
    brand:         "Adidas",
    images:        [
      "https://m.media-amazon.com/images/I/51zoWKrxmcL._AC_SX575_.jpg",
      "https://m.media-amazon.com/images/I/51mhGeZLZsL._AC_SX575_.jpg",
      "https://m.media-amazon.com/images/I/417gOYU2baL._AC_SX575_.jpg",
      "https://m.media-amazon.com/images/I/514Mt9doOEL._AC_SX575_.jpg",
      "https://m.media-amazon.com/images/I/51fe5vEqhXL._AC_SY575_.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         32,
    specs:         { "Upper": "Primeknit+ with Demonskin", "Sole": "Firm Ground", "Closure": "Lace", "Available Sizes": "39-47", "Weight": "220g" },
    tags:          ["football", "boots", "adidas", "predator"],
    rating:        4.6,
    review_count:  156,
  },

  // ── Gaming (5 products) ─────────────────────────────────────────────────────
  {
    name:          "Xbox Series X Console",
    description:   "The fastest, most powerful Xbox ever. Play thousands of titles across 4 generations of Xbox. Features 12 TFLOPS GPU, 16GB RAM, 1TB NVMe SSD, and 4K gaming at 60fps.",
    price:         420000,
    original_price:475000,
    category:      "gaming",
    category_name: "Gaming",
    brand:         "Microsoft",
    images:        [
      "https://m.media-amazon.com/images/I/61dqP5FflJL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/61dqP5FflJL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/61HqO3q9OIL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/61rw7wU5qYL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/61rw7wU5qYL._SX522_.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:true,
    stock:         14,
    specs:         { "CPU": "AMD Zen 2, 8 cores @ 3.8GHz", "GPU": "12 TFLOPS RDNA 2", "Storage": "1TB NVMe SSD", "RAM": "16GB GDDR6", "Resolution": "Up to 8K" },
    tags:          ["gaming", "xbox", "console", "microsoft"],
    rating:        4.8,
    review_count:  387,
  },
  {
    name:          "Nintendo Switch OLED Model",
    description:   "Enhanced Nintendo Switch with vibrant 7-inch OLED screen, 64GB internal storage, wide adjustable stand, and dock with LAN port for wired internet in TV mode.",
    price:         185000,
    original_price:205000,
    category:      "gaming",
    category_name: "Gaming",
    brand:         "Nintendo",
    images:        [
      "https://m.media-amazon.com/images/I/61nqNujSF2L._SX522_.jpg",
      "https://m.media-amazon.com/images/I/61nqNujSF2L._SX522_.jpg",
      "https://m.media-amazon.com/images/I/6106vjwmtIS._SX522_.jpg",
      "https://m.media-amazon.com/images/I/719EZAc9WHS._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71Sgq7L+AuS._SX522_.jpg",
      "https://m.media-amazon.com/images/I/61z-iuVjhdS._SX522_.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         25,
    specs:         { "Screen": "7\" OLED", "Storage": "64GB", "Battery": "4.5-9 hours", "Resolution": "1920x1080 (TV), 1280x720 (handheld)", "Modes": "TV, Tabletop, Handheld" },
    tags:          ["gaming", "nintendo", "switch", "oled", "portable"],
    rating:        4.7,
    review_count:  298,
  },
  {
    name:          "Razer BlackWidow V4 Pro Mechanical Keyboard",
    description:   "Wireless mechanical gaming keyboard with Razer Yellow switches. Features Chroma RGB, magnetic palm rest, dedicated macro keys, and 200-hour battery life.",
    price:         112000,
    original_price:138000,
    category:      "gaming",
    category_name: "Gaming",
    brand:         "Razer",
    images:        [
      "https://m.media-amazon.com/images/I/81L4FpeS3VL._AC_SX300_SY300_QL70_FMwebp_.jpg",
      "https://m.media-amazon.com/images/I/71lyFrcQ0HL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/71qntGdDckL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/81W4hslvStL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/81XQaC7vX+L._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/71OEqY51LeL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81biEkzFFVL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61raLDzUG-L._AC_SL1500_.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         28,
    specs:         { "Switch": "Razer Yellow (Linear)", "Connectivity": "Wireless 2.4GHz / Bluetooth", "Battery": "200 hours", "Backlighting": "Chroma RGB", "Layout": "Full-size with numpad" },
    tags:          ["keyboard", "gaming", "razer", "mechanical", "wireless"],
    rating:        4.5,
    review_count:  143,
  },
  {
    name:          "Meta Quest 3 VR Headset 128GB",
    description:   "The most powerful Quest headset yet with breakthrough mixed reality, pancake lenses, and next-generation Snapdragon XR2 Gen 2 chip. Requires no PC or phone.",
    price:         350000,
    original_price:390000,
    category:      "gaming",
    category_name: "Gaming",
    brand:         "Meta",
    images:        [
      "https://m.media-amazon.com/images/I/715Y5bLr3RL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/715FiAdZwwL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/716g4KaMf9L._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71vZmbodoOL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71AoZa5zlsL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/718m-3qoMDL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/813KSWf5epL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61yurA1+SQL._SL1500_.jpg",
    ],
    badge:         "new",
    is_new:        true,
    is_best_seller:false,
    stock:         15,
    specs:         { "Storage": "128GB", "Chip": "Snapdragon XR2 Gen 2", "Display": "2064x2208 per eye, 90Hz", "Battery": "2-3 hours", "Tracking": "6DOF inside-out" },
    tags:          ["vr", "meta", "quest", "virtual-reality", "gaming"],
    rating:        4.6,
    review_count:  112,
  },
  {
    name:          "Logitech G Pro X Superlight 2 Gaming Mouse",
    description:   "Ultra-lightweight wireless gaming mouse at 60g. Features HERO 2 25K DPI sensor, 95-hour battery, and LIGHTSPEED 2 wireless for sub-1ms response time.",
    price:         58000,
    original_price:72000,
    category:      "gaming",
    category_name: "Gaming",
    brand:         "Logitech",
    images:        [
      "https://m.media-amazon.com/images/I/51Cps60NQpL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/61C1qwVNamL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/810kkuWpvLL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71jjVeUc0DL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/71txNxYWSTL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/718kxZfGH2L._AC_SL1500_.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         55,
    specs:         { "Weight": "60g", "Sensor": "HERO 2, 25K DPI", "Connectivity": "LIGHTSPEED 2.4GHz", "Battery": "95 hours", "Buttons": "5 programmable" },
    tags:          ["mouse", "gaming", "logitech", "wireless", "esports"],
    rating:        4.8,
    review_count:  267,
  },

  // ── Books (4 products) ──────────────────────────────────────────────────────
  {
    name:          "Atomic Habits by James Clear",
    description:   "The #1 New York Times bestseller. A revolutionary system to get 1 per cent better every day. Learn how tiny changes lead to remarkable results in every area of your life.",
    price:         4200,
    original_price:5500,
    category:      "books",
    category_name: "Books",
    brand:         "Penguin Random House",
    images:        [
      "https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/17/5352752/1.jpg?4989",
      "https://m.media-amazon.com/images/I/71F4+7rk2eL._SL1500_.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:true,
    stock:         200,
    specs:         { "Author": "James Clear", "Pages": "320", "Publisher": "Penguin Random House", "Year": "2018", "Format": "Paperback" },
    tags:          ["self-help", "habits", "productivity", "bestseller"],
    rating:        4.9,
    review_count:  2341,
  },
  {
    name:          "Rich Dad Poor Dad by Robert Kiyosaki",
    description:   "The #1 personal finance book of all time. What the rich teach their kids about money that the poor and middle class do not. Updated with new commentary for today's world.",
    price:         3800,
    original_price:5000,
    category:      "books",
    category_name: "Books",
    brand:         "Plata Publishing",
    images:        [
      "https://m.media-amazon.com/images/I/61BzTcF1ADL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/814XbqXAz-L._SL1500_.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:true,
    stock:         180,
    specs:         { "Author": "Robert T. Kiyosaki", "Pages": "336", "Publisher": "Plata Publishing", "Year": "1997 (2017 edition)", "Format": "Paperback" },
    tags:          ["finance", "investing", "bestseller", "money"],
    rating:        4.7,
    review_count:  3120,
  },
  {
    name:          "Things Fall Apart by Chinua Achebe",
    description:   "Africa's most widely read novel. The story of Okonkwo, a proud warrior of the Igbo tribe in Nigeria, during the arrival of European missionaries. A literary masterpiece.",
    price:         2800,
    original_price:null,
    category:      "books",
    category_name: "Books",
    brand:         "Heinemann Educational",
    images:        [
      "https://m.media-amazon.com/images/I/91NtvTU0xEL._SY466_.jpg",
      "https://m.media-amazon.com/images/I/91NtvTU0xEL._SY466_.jpg",
    ],
    badge:         null,
    is_new:        false,
    is_best_seller:true,
    stock:         250,
    specs:         { "Author": "Chinua Achebe", "Pages": "224", "Publisher": "Heinemann", "Year": "1958", "Format": "Paperback" },
    tags:          ["fiction", "african-literature", "chinua-achebe", "classic", "nigerian"],
    rating:        4.8,
    review_count:  1856,
  },
  {
    name:          "Purple Hibiscus by Chimamanda Ngozi Adichie",
    description:   "A stunning debut novel by one of Nigeria's most celebrated authors. Set in post-colonial Nigeria, it follows 15-year-old Kambili and her family's journey through turmoil and grace.",
    price:         3200,
    original_price:4000,
    category:      "books",
    category_name: "Books",
    brand:         "Algonquin Books",
    images:        [
      "https://m.media-amazon.com/images/I/81nJUluy7cL._SY466_.jpg",
      "https://m.media-amazon.com/images/I/81thD3lFDcL._SY466_.jpg",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         120,
    specs:         { "Author": "Chimamanda Ngozi Adichie", "Pages": "307", "Publisher": "Algonquin Books", "Year": "2003", "Format": "Paperback" },
    tags:          ["fiction", "nigerian-literature", "adichie", "africa"],
    rating:        4.7,
    review_count:  872,
  },

  // ── Automotive (2 products) ─────────────────────────────────────────────────
  {
    name:          "Meguiar's Ultimate Compound Car Polish",
    description:   "Professional-grade paint compound that removes light to moderate paint defects, scratches, water spots, and oxidation. Safe for all types of paint and finishes.",
    price:         6500,
    original_price:8500,
    category:      "automotive",
    category_name: "Automotive",
    brand:         "Meguiar's",
    images:        [
      "https://www.meguiars.com/sites/default/files/styles/colorbox_image/public/2025-11/G15816_UltimateBlack_Hero_web.png?itok=sAQjCvlx",
      "https://www.meguiars.com/sites/default/files/styles/colorbox_image/public/2025-11/Bplus_08_Formula_Technology-G15816%20Ultimate%20Black%2016%20oz.jpg?itok=Y_IUgK7y",
      "https://www.meguiars.com/sites/default/files/styles/colorbox_image/public/2025-11/Bplus_06_How_to-G15816%20Ultimate%20Black%2016%20oz.jpg?itok=IhvN5qBC",
      "https://www.meguiars.com/sites/default/files/styles/colorbox_image/public/2025-11/Bplus_05_Before_After-G15816%20Ultimate%20Black%2016%20oz.jpg?itok=FnLRCs-v",
      "https://www.meguiars.com/sites/default/files/styles/colorbox_image/public/2025-11/Bplus_03_Solutions-G15816%20Ultimate%20Black%2016%20oz.jpg?itok=BdJd5Q-f",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         95,
    specs:         { "Size": "450g", "Application": "Hand or machine", "Finish": "All paint types", "Use Case": "Remove scratches, oxidation", "Safe For": "Clear coat, single stage" },
    tags:          ["car-care", "polish", "meguiars", "detailing"],
    rating:        4.6,
    review_count:  412,
  },
  {
    name:          "Nextbase 522GW Dash Cam Front & Rear",
    description:   "1080p front and rear dash cam with Alexa built-in, Emergency SOS, what3words location sharing, and 3\" HD touchscreen. Includes rear window camera.",
    price:         48000,
    original_price:60000,
    category:      "automotive",
    category_name: "Automotive",
    brand:         "Nextbase",
    images:        [
      "https://i.shgcdn.com/a2fb81c8-ca43-455f-b5e6-7c1c91c7d96a/-/format/auto/-/quality/best/",
      "https://i.shgcdn.com/f5a729b8-7410-4ee2-b0be-0bc63420ff3c/-/format/auto/-/preview/3000x3000/-/quality/lighter/",
      "https://i.shgcdn.com/fbc8b5e8-c89a-4828-bf7f-f7a0672b3af7/-/format/auto/-/preview/3000x3000/-/quality/best/",
      "https://i.shgcdn.com/717d04ea-811b-4150-a915-114d8faeaa85/-/format/auto/-/quality/best/",
      "https://i.shgcdn.com/2192ed53-6a23-4d96-a5a8-5f352b20a357/-/resize/1080x/",
    ],
    badge:         "sale",
    is_new:        false,
    is_best_seller:false,
    stock:         40,
    specs:         { "Resolution": "1080p front + rear", "Screen": "3\" HD Touch", "Field of View": "140° front, 140° rear", "Night Vision": "Yes", "Emergency SOS": "Yes" },
    tags:          ["dash-cam", "car", "nextbase", "automotive", "safety"],
    rating:        4.5,
    review_count:  187,
  },
];

// ─── SEED FUNCTION ────────────────────────────────────────────────────────────
async function seed() {
  const client = await pool.connect();

  try {
    await client.query("BEGIN");

    // 1. Clear existing data (order matters due to FK constraints)
    console.log("🗑️  Clearing existing data...");
    await client.query("DELETE FROM order_items");
    await client.query("DELETE FROM orders");
    await client.query("DELETE FROM wishlist");
    await client.query("DELETE FROM reviews");
    await client.query("DELETE FROM products");
    await client.query("DELETE FROM user_addresses");
    await client.query("DELETE FROM users");

    // 2. Seed products
    console.log(`📦 Inserting ${PRODUCTS.length} products...`);
    for (const p of PRODUCTS) {
      await client.query(
        `INSERT INTO products
           (name, description, price, original_price, category, category_name,
            brand, images, videos, badge, is_new, is_best_seller, stock, specs, tags, rating, review_count)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)`,
        [
          p.name,
          p.description,
          p.price,
          p.original_price,
          p.category,
          p.category_name,
          p.brand,
          p.images,
          p.videos || [],
          p.badge,
          p.is_new,
          p.is_best_seller,
          p.stock,
          JSON.stringify(p.specs),
          p.tags,
          p.rating,
          p.review_count,
        ]
      );
    }

    // 3. Seed admin user
    console.log("👤 Creating admin user...");
    const adminHash = await argon2.hash("Admin@NexMart1", {
      type:        argon2.argon2id,
      memoryCost:  2 ** 16,
      timeCost:    3,
      parallelism: 1,
    });
    await client.query(
      `INSERT INTO users (name, email, password, role)
       VALUES ($1, $2, $3, $4)`,
      ["NexMart Admin", "admin@nexmart.com", adminHash, "admin"]
    );

    // 4. Seed test user
    console.log("👤 Creating test user...");
    const userHash = await argon2.hash("Test@User123", {
      type:        argon2.argon2id,
      memoryCost:  2 ** 16,
      timeCost:    3,
      parallelism: 1,
    });
    await client.query(
      `INSERT INTO users (name, email, password, role, loyalty_points)
       VALUES ($1, $2, $3, $4, $5)`,
      ["Chisom Adeyemi", "test@nexmart.com", userHash, "user", 450]
    );

    await client.query("COMMIT");

    console.log("\n✅ Seed complete!");
    console.log(`   📦 ${PRODUCTS.length} products inserted`);
    console.log(`   👤 Admin: admin@nexmart.com / Admin@NexMart1`);
    console.log(`   👤 Test:  test@nexmart.com  / Test@User123`);
    console.log("\n   Categories seeded:");
    const cats = [...new Set(PRODUCTS.map((p) => p.category_name))];
    cats.forEach((c) => {
      const count = PRODUCTS.filter((p) => p.category_name === c).length;
      console.log(`     • ${c}: ${count} products`);
    });

  } catch (err) {
    await client.query("ROLLBACK");
    console.error("\n❌ Seed failed:", err.message);
    throw err;
  } finally {
    client.release();
    await pool.end();
  }
}

seed();
